---
title: "TASK 2: Mini “exploratory report” on juvenile snowshoe hares in Bonanza Creek Experimental Forest "
author: "Author: Sage Davis"
date: "11/7/2021"
output: html_document
---


```{r setup, include = FALSE, , message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
 
library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(kableExtra)
library(effsize)
library(ggbeeswarm)

```

```{r}
# Read in hare bonanza data

hares <- read_csv(here("data", "bonanza_hares.csv"))

hares
```


```{r}
# 3) c) i)

# Convert date to date format, add column for day and year

hares_date <- hares %>%        
  mutate(date = mdy(date)) %>%    
  mutate(day = day(date)) %>%     
  mutate(year = year(date))       

# Count annual hare traps, filter for juveniles
  
hares_juv <- hares_date %>%    
  filter(age == "j")        

# Create Table Summarize by year

hares_juv_count <- hares_juv %>% 
  group_by(year) %>% 
  summarize(juv_count = n())    

# Create finalized data visualization

ggplot(data = hares_juv_count, aes(x = year, y = juv_count)) +
  geom_col(fill = "yellow", color = "blue") + 
  theme_minimal() +
  labs(x = "Year", y = "Annual Juvenile Hare Trappings")


  
```

**Figure 1.**  Annual juvenile hare observations during 1998 - 2012 at Bonanza Creek LTER, Alaska.  Kielland, et al. (2017)  




```{r}
# 3) c) ii)

ggplot(data = hares_juv, aes(x = sex, y = weight, color = grid)) +   # Plot points sex vs. weight
  geom_beeswarm() +
  theme_minimal() +
  facet_wrap(~grid) +                                               # split plots by sampling site
  labs(x = "Sex", y = "Weight (g)", 
       title = "Juvenile Hare Weights vs Sex for Three Sampling Sites", 
       legend.title = "Sampling Site") +
  scale_color_discrete(name = "Sampling Site")
                      #labels = c("bonanza1", "bonanza2", "bonanza3"))                        # rename legend


```
Description:


```{r}

# 3) c) iii)

hares_juv_sex <- hares_juv %>%   # Start with hares_juv dataset
  filter(!is.na(sex))           # Remove sex with NA in cell

hares_juv_weights <- hares_juv_sex %>%   # Start with hares_juv_sex dataset
  group_by(sex) %>% 
  summarize(wt_mean = round(mean(weight, na.rm = TRUE), 1),  # Create table by sex for various weight stats
           wt_sd = round(sd(weight, na.rm = TRUE), 1),      # Round data 
           sample_size = n())
# Exploratory Code and Plots

ggplot(data = hares_juv_sex, aes(x = weight, color = sex)) +   # Plot points sex vs. weight
  geom_histogram() +
  facet_wrap(~grid)

ggplot(data = hares_juv_sex, aes(sample = weight)) +
  geom_qq() +
  facet_wrap(~grid)

# Previous Plot - Histogram does not really look normally distributed but QQ-plot looks ok

ggplot(data = hares_juv_sex, aes(x = weight, color = grid)) +   # Plot points sex vs. weight
  geom_histogram() +
  facet_wrap(~sex)

ggplot(data = hares_juv_sex, aes(sample = weight)) +
  geom_qq() +
  facet_wrap(~sex)

# Previous plot - Female looks more normally distributed

hares_juv_f <- hares_juv_sex %>% 
  filter(sex == "f") %>% 
  select(weight)

hares_juv_m <- hares_juv_sex %>% 
  filter(sex == "m") %>% 
  select(weight)

hares_juv_wt_sex_t <- t.test(hares_juv_m, hares_juv_f)

round(hares_juv_wt_sex_t$estimate, 2)


# weight_cohen <- cohen.d(hares_juv_m, hares_juv_f, na.rm = TRUE)  ##not working - 1st paramter not numeric - do I need to remove na

# How do you for split up columns or from different datasets?


hares_juv_f

```


```{r}
 # 3) c) iii) Table

hares_juv_weights_table <- hares_juv_weights %>%                   # Finalize Table
  kable(col.names = c("Hare Sex",
                      "Mean Weight (g)", 
                      "Standard Deviation (g)",
                      "Sample size (n)"), 
        caption = "Female & Male Juvenile Hare Weight Means and Standard Deviations") %>% 
  kable_styling(full_width = FALSE)

```
  
  Statement here:
  
```{r}

# 3) c) iv) - Relationship between Juvenile weight & hind foot length (mm)

# hares_juv_wt_hr <- hares_juv  %>%  # start with hares_juv data
ggplot(data = hares_juv, aes(x = hindft, y = weight, color = sex)) +
  geom_point() +
  theme_minimal() +
  labs(x = "Hindfoot Length (mm)", y = "Hare Weight (g)") +
  scale_color_discrete(name = "Sex",                       # formulas say _fill_?
                      labels = c("Female", "Male", "Undetermined"))     




```
  
```{r}
# Boss asks for linear regression of Weight vs Hindfoot Length

hares_juv_lm <- lm(weight ~ hindft, data = hares_juv)

summary(hares_juv_lm)


```

The linear regression showed that on average the weight of the hare will increase by `r round(hares_juv_lm$coefficient[2], 2)` grams per mm of hindfoot increase.
